#!/bin/bash

brew install --cask \
    adobe-acrobat-reader \
    adobe-creative-cloud \
    authy \
    balenaetcher \
    bitwarden \
    brave-browser \
    docker \
    firefox \
    insomnia \
    iterm2 \
    jetbrains-toolbox \
    kdrive \
    macvim \
    microsoft-excel \
    microsoft-word \
    signal \
    sourcetree \
    virtualbox \
    vlc \
    vscodium
